# basic options
title: Anh Pham
#author: GitHub User
#email: ngoc.t.pham@adelaide.edu.au
email: anhpham.econ@gmail.com
description: Research Officer at University of Adelaide
#twitter_username: jekyllrb
github_username:  anhpham-econ
url: https://anhpham-econ.github.io/

# Build settings
markdown: kramdown
#theme: jekyll-theme-minimal
theme: minima
